# SpringBoot核心配置文件
server:
  port: 8084

person:
  name: mousezhang@188.com
  age: ${random.int}
  birthday: 2020/02/02
  salary: 10000.0
  lists:
    - code
    - music
    - girl
  dog:
    name: 咪咪${random.uuid}
    age: 1
  maps: {k1: v1,k2: v2}
# SpringBoot的多环境配置，可以选择激活哪个配置
spring:
  profiles:
    active: dev

---
# debug: true # 查看SpringBoot自动装配了哪个类
server:
  port: 8090
spring:
  profiles: dev

---
server:
  port: 8091
spring:
  profiles: test
