spring:
  datasource:
    username: root
    password: root123
    url: jdbc:mysql://localhost:3306/springboot?serverTimezone=UTC&useUnicode=ture&characterEncoding=utf-8
    driver-class-name: com.mysql.cj.jdbc.Driver
# 整合mybatis
mybatis:
  type-aliases-package: cn.ustb.pojo
  mapper-locations: classpath:mybatis/mapper/*.xml